### ISSUE TITLE
Can the AppImage be downloaded somewhere?

### ISSUE THREAD

**Issue by probonopd** [nuspell/misc-nuspell#3]
Hi, thanks for making an AppImage. Can it be downloaded somewhere?

**Comment by PanderMusubi** [comment]
Soon, will post here when it becomes available. On what platform/OS/distro are you planning to use it?

**Comment by probonopd** [comment]
Cool, thanks :+1:  
The oldest still-supported LTS of Ubuntu, which currently is Ubuntu xenial.

**Comment by PanderMusubi** [comment]
Unfortunately, we don't support Xenial as the combination of versions of dependencies (cmake, libicu, libboost, etc.) are too old for Nuspell. Bionic is the oldest Ubuntu LTS we can support. There it is better to install Nuspell via our PPA for ease of updates.

**Comment by probonopd** [comment]
Maybe @azubieta could look into this, he has tools that can handle this situation.

**Comment by azubieta** [comment]
Hi @PanderMusubi !
You may want to take a look at [appimage-builder](https://appimage-builder.readthedocs.io/en/latest/). It's a new tool for creating AppImages that allows building your AppImages on modern Ubuntu/Debian systems keeping the backward compatibility.

Let me know if you need help

**Comment by PanderMusubi** [comment]
We are about to release AppImage build with this. It is based on Bionic, but if it runs on Xenial, that would solve your question.

**Comment by PanderMusubi** [comment]
@probonopd We can build AppImage for Bionic and Focal. The once for Bionic probably runs on Xeinal. Can you try this, please?

One last challenge we got here is the following. When uncommenting these lines https://github.com/nuspell/misc-nuspell/blob/2d33d5be18b5a6c37a033fcb2cacf17b7a190dad/packaging/appimage/AppImageBuilderFocal.yml#L4-L5 the building results in the following error: 

    INFO:appimagetool:Trying to validate AppStream information with the appstreamcli tool
    INFO:appimagetool:In case of issues, please refer to https://github.com/ximion/appstream
    WARNING:appimagetool:appimagetool, continuous build (commit df8b13c), build 2121 built on 2020-05-08 09:52:11 UTC
    WARNING:appimagetool:Using architecture x86_64
    WARNING:appimagetool:Deleting pre-existing .DirIcon
    WARNING:appimagetool:Creating .DirIcon symlink based on information from desktop file
    WARNING:appimagetool:AppStream upstream metadata found in usr/share/metainfo/org.nuspell.Nuspell.appdata.xml
    WARNING:appimagetool:/usr/bin/appstreamcli: symbol lookup error: /usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
    WARNING:appimagetool:Failed to validate AppStream information with appstreamcli
    ERROR:root:AppImage generation failed

How can I fix this? I have libsoup2.4 installed. also libsoup-gnome2.4 and both dev packages.

**Comment by azubieta** [comment]
@PanderMusubi it seems that the "appstreamcli" tool is not working properly. Can you try running it manually to check if it's being affected by something in the appimagetool run environment?

As a quick fix, you can remove the appstream file from the bundle.

**Update**:
A comment on the appimage-builder recipe. You can build the app from sources, it's not mandatory to use a debian package as an entry point. That will allow having nightly builds and not depending on Debian packaging.
You can place the build instructions in the script section and replace the "nuspell" package in the include by its dependencies.

**Comment by PanderMusubi** [comment]
@azubieta 

    $ appstreamcli --version
    AppStream version: 0.12.10
    $ dpkg -l |grep appstr
    ii  appstream                                                   0.12.10-2                             amd64        Software component metadata management
    ii  libappstream-glib8:amd64                                    0.7.16-1ubuntu1                       amd64        GNOME library to access AppStream services
    ii  libappstream4:amd64                                         0.12.10-2                             amd64        Library to access AppStream services
    $ appstreamcli validate ../appstream/org.nuspell.Nuspell.metainfo.xml 
    Validation was successful: pedantic: 1

Does this help you pin point the issue?

Thanks for the suggestion on building from source. For now, I will use from the PPA as we don't have nightly's yet.

**Comment by azubieta** [comment]
Ok, It's a bug on appimagetool. Which appimagetool version are you using?

Can you try using https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage

@probonopd ^

**Comment by PanderMusubi** [comment]
$ which appimagetool
    /usr/local/bin/appimagetool
    $ appimagetool --version
    appimagetool, continuous build (commit df8b13c), build 2121 built on 2020-05-08 09:52:11 UTC

Now testing your version

**Comment by PanderMusubi** [comment]
Thanks for creating the issue.

Our AppImage is available at https://github.com/nuspell/nuspell/releases/tag/v3.1.1
