### ISSUE TITLE
Build snap in release mode

### ISSUE THREAD

**Issue by dimztimz** [nuspell/misc-nuspell#4]
The snap misses the cmake option to build in release mode.

**Comment by PanderMusubi** [comment]
Fixed in https://github.com/nuspell/misc-nuspell/blob/master/snap/snapcraft.yaml#L18 Snapcraft is building now.

Is this also needed here? https://github.com/nuspell/misc-nuspell/blob/master/packaging/deb/debian/rules#L11

**Comment by dimztimz** [comment]
> Is this also needed here? https://github.com/nuspell/misc-nuspell/blob/master/packaging/deb/debian/rules#L11

No. But it is needed for the flatpak too. I'll open separate issue.

**Comment by PanderMusubi** [comment]
Will also update Brew, notify packagers, etc.
