### ISSUE TITLE
Snap's package can not load any dictionary

### ISSUE THREAD

**Issue by dimztimz** [nuspell/misc-nuspell#5]
Even when one dictionary is packaged:

https://github.com/nuspell/misc-nuspell/blob/64a65dc8e4b471fc3e8f801f7f1729475f98ca06/snap/snapcraft.yaml#L30

Nuspell does not find this because that dictionary ends up being in: `$SNAP/usr/share/hunpsell` where `$SNAP` is the root of the pacakge, usually located in `/snap/nuspell/current`. Nuspell doesn't look there, instead it looks in the real `/usr/share/hunspell`, but it doesn't have access to it due to [confinement](https://snapcraft.io/docs/snap-confinement).

Something of the following can be done:

1. Use [Snap layouts](https://snapcraft.io/docs/snap-layouts) to "mount" `$SNAP/usr/share/hunpsell` into `/usr/share/hunspell`.
2. Use the environment variable `DICPATH`  that Nuspell understands to point to the directory with dictionaries inside `$SNAP`. You can specify environment variables inside the yaml.
3. [Request read-access](https://snapcraft.io/docs/system-files-interface) to the real `/usr/share/hunspell`. This probably conflicts with 1.
4. Specify more dictionaries as dependencies.
5. Depend on the [special snap with dictionaries](https://snapcraft.io/docs/t/the-hunspell-dictionaries-content-snaps/7160).

Some experimentation with these tasks needs to be done to see which combination works. IMO the final combination should be with points 2, 3, and 5.

**Comment by dimztimz** [comment]
To explain further, I will say that there are three goals that need to be achieved:

- Make Nuspell see the dictionaries inside the Snap's dir. This is achievable with the task 1 or 2.
- Make Nuspell see the system dictionaries installed with Apt. This is achievable with task 3.
- Add more dictionaries in the Snap. This is achievable with the task 4 or 5.

**Comment by dimztimz** [comment]
Once step 3 and step 5 are finished (the plugs and interfaces things), we should proceed with:

- https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks
- https://snapcraft.io/docs/auto-connection-mechanism

**Comment by dimztimz** [comment]
The snap yaml is good as is now. The request for automatic connection should be done now.

**Comment by PanderMusubi** [comment]
Okay.

**Comment by PanderMusubi** [comment]
Can this line be removed? https://github.com/nuspell/misc-nuspell/blob/master/snap/snapcraft.yaml#L45

**Comment by dimztimz** [comment]
Yes, after the automatic connection is approved.

**Comment by PanderMusubi** [comment]
Request has been made.

**Comment by PanderMusubi** [comment]
So far no replies https://forum.snapcraft.io/t/request-autoconnect-for-nuspell/21047

**Comment by dimztimz** [comment]
Ok then, the only usable alternative is to pack all of the dictionaries inside the snap. i don't care if it going to take 100-300 MB, at least it will work. The current snap is unusable.

**Comment by PanderMusubi** [comment]
I've pinged the reviewers. Lets see for a few more days.

**Comment by dimztimz** [comment]
Look like there is some activity on the forum. See that and reply.

**Comment by dimztimz** [comment]
I did some updates as requested on the forum, see c7b190f33e0ad9bcc3c1f439eaf2d8d3b3068d44.
